export const categories = [
  "全部",
  "建材",
  "装备",
  "补给",
  "装饰",
  "建筑服务",
  "其他",
];
export const players = [
  {
    id: "mori",
    name: "Mori",
    qq: "1000101",
    bio: "把每一次日落，留在小花园里。",
    color: "sage",
    admin: true,
  },
  {
    id: "aster",
    name: "Aster",
    qq: "1000103",
    bio: "下一座建筑，正在计划中。",
    color: "blue",
  },
  {
    id: "luna",
    name: "Luna",
    qq: "1000102",
    bio: "探索地图，也收集好风景。",
    color: "purple",
  },
  {
    id: "oak",
    name: "Oak",
    qq: "1000105",
    bio: "专心种田，偶尔钓鱼。",
    color: "amber",
  },
];
export const products = [
  {
    id: "iphone",
    title: "iPhone 17 Pro",
    subtitle: "全 Pro 实力，随心探索。",
    brand: "Apple",
    price: 899900,
    image: "store_iphone.webp",
    tone: "black",
    tag: "本周精选",
    stock: 12,
  },
  {
    id: "macbook",
    title: "MacBook Air",
    subtitle: "轻装上阵，灵感无限。",
    brand: "Apple",
    price: 799900,
    image: "store_macbook.webp",
    tone: "ice",
    tag: "灵感装备",
    stock: 8,
  },
  {
    id: "ipad",
    title: "iPad Air",
    subtitle: "画下你的下一个世界。",
    brand: "Apple",
    price: 479900,
    image: "store_ipad.webp",
    tone: "lavender",
    stock: 15,
  },
  {
    id: "airpods",
    title: "AirPods Max",
    subtitle: "把好声音，留在耳边。",
    brand: "Apple",
    price: 189900,
    image: "store_airpods.webp",
    tone: "white",
    stock: 20,
  },
  {
    id: "watch",
    title: "Apple Watch",
    subtitle: "每一步，都有新发现。",
    brand: "Apple",
    price: 299900,
    image: "store_watch.webp",
    tone: "sand",
    stock: 10,
  },
  {
    id: "rtx5090",
    title: "GeForce RTX 5090",
    subtitle: "让每一个方块，都栩栩如生。",
    brand: "NVIDIA",
    price: 1699900,
    image: "product_rtx5090_1.jpg",
    tone: "mint",
    stock: 4,
  },
  {
    id: "ryzen",
    title: "Ryzen 9 9950X",
    subtitle: "为创造，留足实力。",
    brand: "AMD",
    price: 429900,
    image: "product_ryzen9950_1.png",
    tone: "sand",
    stock: 6,
  },
];
export const seedListings = [
  {
    id: "l1",
    title: "橡木与云杉原木 · 建筑材料包",
    description:
      "新鲜采集的原木，适合搭建温暖的小屋。每份含橡木、云杉木各一组，主城东门约定自取。",
    category: "建材",
    price: 12800,
    stock: 8,
    owner: "oak",
    art: "wood",
    place: "主城东门",
    active: true,
  },
  {
    id: "l2",
    title: "海边小屋 · 定制建筑服务",
    description:
      "一起把想象中的家变成现实。包含建筑设计、施工及室内软装，总工期含验收预留。",
    category: "建筑服务",
    price: 180000,
    stock: 1,
    owner: "aster",
    art: "village",
    place: "主世界 · 海岸新区",
    hours: 168,
    active: true,
  },
  {
    id: "l3",
    title: "钻石镐 · 效率 V / 耐久 III",
    description:
      "附带精准采集，让下一次矿洞探险更轻松。约定自取，请先通过私聊联系。",
    category: "装备",
    price: 68000,
    stock: 2,
    owner: "luna",
    art: "pickaxe",
    place: "主城交易区",
    active: true,
  },
  {
    id: "l4",
    title: "把一片花海带回家",
    description: "绣球色系花卉与装饰植物组合，为庭院添上一点生机。",
    category: "装饰",
    price: 9600,
    stock: 12,
    owner: "luna",
    art: "flowers",
    place: "主城南门",
    active: true,
  },
  {
    id: "l5",
    title: "金胡萝卜 · 远行补给",
    description: "一组 64 个，出发前带上充足的补给。可送至主城范围内。",
    category: "补给",
    price: 6400,
    stock: 16,
    owner: "oak",
    art: "carrot",
    place: "主城范围送货",
    active: true,
  },
  {
    id: "l6",
    title: "暖光灯笼 · 夜晚也温柔",
    description: "一组灯笼，为你的小径与房间添一盏灯。",
    category: "装饰",
    price: 18000,
    stock: 4,
    owner: "mori",
    art: "lantern",
    place: "主城东门",
    active: true,
  },
];
export const seedCommissions = [
  {
    id: "c1",
    title: "一起完成海岸边的小花园",
    description:
      "小屋已经搭好了，想找一位喜欢园艺的朋友一起设计庭院。需要花坛、小径和一处可以看日落的座椅。",
    location: "主世界 · 海岸新区",
    price: 80000,
    hours: 72,
    urgency: "普通",
    owner: "luna",
    status: "OPEN",
    art: "village",
  },
  {
    id: "c2",
    title: "收集一批深板岩建筑材料",
    description:
      "需要 20 组深板岩圆石，用于公共车站扩建。请放入主城车站门口的交付箱。",
    location: "主城 · 中央车站",
    price: 32000,
    hours: 24,
    urgency: "较急",
    owner: "aster",
    status: "OPEN",
    art: "stone",
  },
  {
    id: "c3",
    title: "给新朋友画一张主城地图",
    description:
      "标注交易区、车站和传送点，清楚易读即可。交付一张可供展示的地图。",
    location: "主城 · 公告栏",
    price: 120000,
    hours: 168,
    urgency: "普通",
    owner: "oak",
    status: "OPEN",
    art: "map",
  },
];
export const announcements = [
  {
    id: "a1",
    title: "新旅程，从这里开始。",
    intro: "Deuterium 网页版，和熟悉的朋友在更大的世界里相遇。",
    date: "09 / 08",
    body: "商城、市场、委托、信息和钱包，现在有了各自的空间。所有页面共享同一套视觉和操作习惯。\n\n当前为本机体验版：商品、玩家、消息和交易都是演示内容，所有操作只保存在当前浏览器，不连接游戏经济或真实账号。",
    pinned: true,
  },
  {
    id: "a2",
    title: "让每一份约定，都有回应",
    intro: "了解市场担保与委托验收，放心创造，一起完成。",
    date: "09 / 06",
    body: "市场交易由平台担保，确认收货后再结算。委托提交完成后有独立的 72 小时验收期。\n\n请在交易前确认地点、交付方式及期限，遇到问题先沟通，并保留必要证据。此页面展示产品规则，体验版不执行真实结算。",
  },
];
export const initialMessages = [
  {
    id: "m1",
    channel: "public",
    sender: "luna",
    text: "海岸边的新花园差不多完工了，欢迎来看看 🌿",
    time: "14:20",
  },
  {
    id: "m2",
    channel: "public",
    sender: "aster",
    text: "刚好准备扩建小屋！晚一点一起过去。",
    time: "14:22",
  },
  {
    id: "m3",
    channel: "public",
    sender: "oak",
    text: "我带一点花和灯笼，晚上应该会很好看。",
    time: "14:24",
  },
  {
    id: "m4",
    channel: "dm:luna:mori",
    sender: "luna",
    text: "你的小屋想用什么颜色的花？我这里还有一些蓝色的。",
    time: "13:40",
  },
];
