package com.deuterium.app.uilab

import org.junit.Assert.*
import org.junit.Test
import java.time.*
import java.util.concurrent.*

class CommissionBookTest {
    private class Time(var value:Instant=Instant.parse("2026-09-08T00:00:00Z")):Clock(){override fun getZone():ZoneId=ZoneOffset.UTC;override fun withZone(zone:ZoneId)=this;override fun instant()=value;fun hours(n:Long){value=value.plusSeconds(n*3600)}}
    private val time=Time();private var cash=100000L
    private val notices=mutableListOf<TradeNotice>()
    private fun draft()=CommissionDraft("布置花园","在步道两边补充灯笼和花圃","出生点花园",10000,48,Urgency.Normal,"file:///cover.png")
    private fun book(user:String="Owner")=CommissionBook(user,{cash},{delta,_,_->cash+=delta},time){notices.add(it)}
    private fun publish(book:CommissionBook)=book.publish("once",draft())!!
    @Test fun prepaymentIsAtomicAndIdempotent(){val book=book();val id=publish(book);assertEquals(90000L,cash);assertEquals(10000L,book.heldForUser);assertEquals(id,publish(book));assertEquals(90000L,cash);assertNull(book.publish("once",draft().copy(reward=20000)));assertEquals(1,book.entries.size)}
    @Test fun insufficientFundsDoNotPublish(){cash=9999;val book=book();assertNull(book.publish("once",draft()));assertEquals(9999L,cash);assertTrue(book.entries.isEmpty())}
    @Test fun invalidDraftNeverDeducts(){val book=book();assertNull(book.publish("bad",draft().copy(coverUri=null)));assertNull(book.publish("bad",draft().copy(reward=0)));assertNull(book.publish("bad",draft().copy(workHours=0)));assertEquals(100000L,cash)}
    @Test fun onlyOneOtherPlayerCanAccept(){val book=book();val id=publish(book);assertFalse(book.accept(id,"Owner"));assertTrue(book.accept(id,"Worker"));assertFalse(book.accept(id,"Other"));assertEquals("Worker",book.find(id)!!.worker);assertEquals(90000L,cash)}
    @Test fun simultaneousAcceptsChooseOneWorker(){val book=book();val id=publish(book);val start=CountDownLatch(1);val pool=Executors.newFixedThreadPool(2);try{val results=listOf("A","B").map{name->pool.submit<Boolean>{start.await();book.accept(id,name)}};start.countDown();assertEquals(1,results.count{it.get(3,TimeUnit.SECONDS)})}finally{pool.shutdownNow()}}
    @Test fun acceptanceStartsWorkClockAndLateWorkDoesNotSettle(){val book=book();val id=publish(book);time.hours(10);book.accept(id,"Worker");assertEquals(time.millis()+48*3600000L,book.find(id)!!.deadlineMillis);time.hours(60);book.advanceTime();assertEquals(CommissionStage.Active,book.find(id)!!.stage);assertTrue(book.payments.isEmpty());assertFalse(book.confirm(id,"Owner"))}
    @Test fun completionNeedsWorkerAndStartsNew72Hours(){val book=book();val id=publish(book);book.accept(id,"Worker");time.hours(40);assertFalse(book.complete(id,"Owner","已完成"));assertFalse(book.complete(id,"Worker"," "));assertTrue(book.complete(id,"Worker","灯笼全部放好，请核对"));assertEquals(time.millis()+72*3600000L,book.find(id)!!.deadlineMillis);assertEquals(CommissionStage.Completed,book.find(id)!!.stage);assertFalse(book.complete(id,"Worker","重复提交"))}
    @Test fun ownerConfirmationSettlesOnlyOnce(){val book=book();val id=publish(book);book.accept(id,"Worker");book.complete(id,"Worker","已完成");assertFalse(book.confirm(id,"Worker"));assertTrue(book.confirm(id,"Owner"));assertFalse(book.confirm(id,"Owner"));time.hours(100);book.advanceTime();assertEquals(10000L,book.payments["Worker"]);assertEquals(0L,book.heldForUser)}
    @Test fun workerReceivesMoneyOnlyAfterConfirmation(){val source=book();val id=publish(source);source.accept(id,"Worker");source.complete(id,"Worker","已完成");val worker=book("Worker");worker.restore(source.entries.toList(),emptyMap(),source.nextSequence);val before=cash;time.hours(72);worker.advanceTime();assertEquals(before+10000,cash);worker.advanceTime();assertEquals(before+10000,cash);assertTrue(worker.find(id)!!.automatic)}
    @Test fun cancellingUnclaimedWorkRefundsExactlyOnce(){val book=book();val id=publish(book);assertFalse(book.cancel(id,"Other"));assertTrue(book.cancel(id,"Owner"));assertEquals(100000L,cash);assertFalse(book.cancel(id,"Owner"));assertFalse(book.accept(id,"Worker"));assertEquals(0L,book.heldForUser)}
    @Test fun acceptedWorkCannotBeCancelledUnilaterally(){val book=book();val id=publish(book);book.accept(id,"Worker");assertFalse(book.cancel(id,"Owner"));assertEquals(90000L,cash)}
    @Test fun refundPausesAcceptanceAndRejectionRequiresReason(){val book=book();val id=publish(book);book.accept(id,"Worker");book.complete(id,"Worker","已完成");time.hours(24);assertTrue(book.requestRefund(id,"Owner","内容不符"));assertEquals(48*3600000L,book.find(id)!!.pausedMillis);time.hours(100);book.advanceTime();assertFalse(book.confirm(id,"Owner"));assertFalse(book.resolveRefund(id,"Worker",false," "));assertEquals(RefundState.Requested,book.find(id)!!.refund);assertTrue(book.resolveRefund(id,"Worker",false,"已按双方确认的方案完成"));assertEquals(time.millis()+48*3600000L,book.find(id)!!.deadlineMillis);assertFalse(book.requestRefund(id,"Owner","再次申请"))}
    @Test fun refundApprovalReturnsMoneyWithoutLaterSettlement(){val book=book();val id=publish(book);book.accept(id,"Worker");book.requestRefund(id,"Owner","要求变更");assertTrue(book.resolveRefund(id,"Worker",true));assertEquals(100000L,cash);time.hours(200);book.advanceTime();assertTrue(book.payments.isEmpty());assertFalse(book.complete(id,"Worker","仍提交完成"));assertEquals(CommissionStage.Cancelled,book.find(id)!!.stage)}
    @Test fun withdrawnRefundDoesNotRestoreAttempt(){val book=book();val id=publish(book);book.accept(id,"Worker");book.requestRefund(id,"Owner","申请协商");assertTrue(book.withdrawRefund(id,"Owner"));assertFalse(book.requestRefund(id,"Owner","再次申请"));assertTrue(book.complete(id,"Worker","已按原约定完成"))}
    @Test fun restoredCompletedWorkSettlesAtOriginalDeadline(){val book=book();val id=publish(book);book.accept(id,"Worker");book.complete(id,"Worker","已完成");val restored=book();restored.restore(book.entries.toList(),book.payments.toMap(),book.nextSequence);time.hours(73);restored.advanceTime();restored.advanceTime();assertEquals(CommissionStage.Confirmed,restored.find(id)!!.stage);assertEquals(10000L,restored.payments["Worker"])}
    @Test fun noticesTargetTheCorrectParticipant(){val book=book();val id=publish(book);book.accept(id,"Worker");book.complete(id,"Worker","已完成");assertTrue(notices.any{it.recipient=="Owner"&&it.kind=="commission_completed"});book.confirm(id,"Owner");assertTrue(notices.any{it.recipient=="Worker"&&it.kind=="commission_settled"})}
}
