package com.deuterium.app.uilab

import org.junit.Assert.*
import org.junit.Test
import java.time.*

class CommerceTimingTest {
    private class MutableTime(var value:Instant=Instant.parse("2026-09-07T00:00:00Z")):Clock(){override fun getZone():ZoneId=ZoneOffset.UTC;override fun withZone(zone:ZoneId):Clock=this;override fun instant():Instant=value;fun hours(n:Long){value=value.plusSeconds(n*3600)}}
    private val time=MutableTime();private var cash=100000L
    private fun listing(service:Boolean=false)=MarketListing("item","测试商品","简介","交付说明",if(service)"建筑服务 · 住宅代建" else "建材 · 石材",10000,3,"Mori","1000101",if(service)setOf(DeliveryMethod.Worksite) else setOf(DeliveryMethod.Pickup),"出生点",imageUri="file:///cover.png",workHours=120)
    private fun book(service:Boolean=false,user:String="Buyer")=CommerceBook(user,listOf(listing(service)),{cash},{delta,_,_->cash+=delta},time)
    private fun buy(book:CommerceBook,service:Boolean=false)=book.buyMarket("one","item",1,if(service)DeliveryMethod.Worksite else DeliveryMethod.Pickup,"出生点",projectName=if(service)"湖畔小屋" else "")!!

    @Test fun goodsConfirmAt72HoursAndOnlyOnce(){val book=book();val id=buy(book);book.ship(id,"Mori");time.hours(71);book.advanceTime();assertEquals(OrderStage.Shipped,book.order(id)!!.stage);time.hours(1);book.advanceTime();assertEquals(OrderStage.Confirmed,book.order(id)!!.stage);assertTrue(book.order(id)!!.automatic);book.advanceTime();assertEquals(10000L,book.sellerPayments["Mori"]);assertEquals(0L,book.heldTotal)}
    @Test fun constructionClockStartsAtConstructionNotPurchase(){val book=book(true);val id=buy(book,true);time.hours(48);book.ship(id,"Mori");assertEquals(time.millis()+120*3600000L,book.order(id)!!.deadlineMillis);assertEquals("开始施工",book.order(id)!!.shipLabel);assertEquals("确认验收",book.order(id)!!.receiptLabel);time.hours(119);book.advanceTime();assertEquals(OrderStage.Shipped,book.order(id)!!.stage);time.hours(1);book.advanceTime();assertEquals("已验收",book.order(id)!!.status)}
    @Test fun projectRequiresNameAndWorksite(){val book=book(true);assertNull(book.buyMarket("a","item",1,DeliveryMethod.Worksite,"出生点"));assertNull(book.buyMarket("b","item",1,DeliveryMethod.Pickup,"出生点",projectName="工程"));assertNull(book.buyMarket("c","item",1,DeliveryMethod.Worksite,"",projectName="工程"));assertEquals(100000L,cash)}
    @Test fun pendingRefundPausesAndRejectionResumesRemainingTime(){val book=book();val id=buy(book);book.ship(id,"Mori");time.hours(24);book.requestRefund(id,"Buyer","先协商");assertNull(book.order(id)!!.deadlineMillis);assertEquals(48*3600000L,book.order(id)!!.pausedMillis);time.hours(240);book.advanceTime();assertEquals(RefundState.Requested,book.order(id)!!.refund);assertEquals(10000L,book.heldTotal);book.resolveRefund(id,"Mori",false,"已按约定交付，请核对物品");assertEquals(time.millis()+48*3600000L,book.order(id)!!.deadlineMillis);assertFalse(book.order(id)!!.canRefund);time.hours(48);book.advanceTime();assertEquals(OrderStage.Confirmed,book.order(id)!!.stage)}
    @Test fun shippedRefundCannotBeRequestedAgainAfterRejection(){val book=book();val id=buy(book);book.ship(id,"Mori");assertTrue(book.requestRefund(id,"Buyer","第一次"));book.resolveRefund(id,"Mori",false,"已按约定交付，请核对物品");assertFalse(book.requestRefund(id,"Buyer","第二次"));assertEquals(1,book.order(id)!!.refundAttempts);assertEquals(90000L,cash)}
    @Test fun withdrawingUsesTheOnlyRefundChance(){val book=book();val id=buy(book);book.ship(id,"Mori");book.requestRefund(id,"Buyer","申请");assertTrue(book.cancelRefund(id,"Buyer"));assertFalse(book.requestRefund(id,"Buyer","再申请"));assertEquals(1,book.order(id)!!.refundAttempts);assertTrue(book.confirmReceipt(id,"Buyer"))}
    @Test fun sellerAndBuyerGetCorrectRefundNotices(){val book=book();val id=buy(book);assertTrue(book.notices.any{it.recipient=="Mori"&&it.kind=="new_order"});book.ship(id,"Mori");book.requestRefund(id,"Buyer","不符");assertTrue(book.notices.any{it.recipient=="Mori"&&it.kind=="refund_request"&&it.orderId==id});assertTrue(book.notices.any{it.recipient=="Buyer"&&it.kind=="refund_submitted"});book.resolveRefund(id,"Mori",true);assertTrue(book.notices.any{it.recipient=="Buyer"&&it.kind=="refund_approved"});assertEquals(100000L,cash)}
    @Test fun expiredOrderCannotStartARefund(){val book=book();val id=buy(book);book.ship(id,"Mori");time.hours(73);assertFalse(book.requestRefund(id,"Buyer","超时"));assertEquals(OrderStage.Confirmed,book.order(id)!!.stage);assertEquals(10000L,book.sellerPayments["Mori"])}
    @Test fun manualConfirmationPreventsSecondAutomaticSettlement(){val book=book();val id=buy(book);book.ship(id,"Mori");book.confirmReceipt(id,"Buyer");time.hours(80);book.advanceTime();assertEquals(10000L,book.sellerPayments["Mori"]);assertFalse(book.order(id)!!.automatic)}
    @Test fun restoredAbsoluteDeadlineSettlesOnResume(){val book=book();val id=buy(book);book.ship(id,"Mori");val restored=book();restored.restore(book.listings.toList(),book.orders.toList(),book.notices.toList(),book.sellerPayments.toMap(),book.nextSequence);time.hours(80);restored.advanceTime();assertEquals(OrderStage.Confirmed,restored.order(id)!!.stage);restored.advanceTime();assertEquals(10000L,restored.sellerPayments["Mori"])}
    @Test fun publisherAccepts999AndFivePhotosButRejectsOverflow(){val book=book(user="Mori");val five=List(5){"file:///photo$it.png"};assertTrue(book.publish(listing().copy(id="new",stock=999,imageUris=five)));assertFalse(book.publish(listing().copy(id="big",stock=1000)));assertFalse(book.publish(listing().copy(id="six",imageUris=five+"file:///six.png")))}
    @Test fun relistingKeepsTheOldContractSnapshot(){val book=book(user="Mori");val id=book.buyMarket("x","item",1,DeliveryMethod.Pickup,"出生点",buyer="Buyer")!!;book.setListingActive("item",false);assertTrue(book.republish(book.listings.single().copy(title="改后的名称",price=20000)));assertEquals("测试商品",book.order(id)!!.lines.single().title);assertEquals(10000L,book.order(id)!!.amount);assertTrue(book.listings.single().active)}
    @Test fun refundAndInventoryReservationStayWithinTheStockLimit(){val book=book(user="Mori");val id=book.buyMarket("x","item",1,DeliveryMethod.Pickup,"出生点",buyer="Buyer")!!;assertFalse(book.republish(book.listings.single().copy(stock=999)));assertTrue(book.republish(book.listings.single().copy(stock=998)));book.requestRefund(id,"Buyer","取消");assertEquals(999,book.listings.single().stock)}
}
