package com.deuterium.app.uilab

import org.junit.Assert.*
import org.junit.Test
import java.time.*
import java.util.concurrent.*

class InterventionBookTest {
    private class Time(var value:Instant=Instant.parse("2026-09-08T00:00:00Z")):Clock(){override fun getZone():ZoneId=ZoneOffset.UTC;override fun withZone(zone:ZoneId)=this;override fun instant()=value;fun hours(n:Long){value=value.plusSeconds(n*3600)}}
    private val time=Time();private var cash=100000L
    private val reason="双方交付记录核对完毕，按实际完成比例处理。"
    private fun form()=InterventionForm(InterventionReason.NotAsDescribed,"收到的商品数量与原约定不符，协商退款被拒。",InterventionWish.FullRefund,null,listOf("file:///evidence.png"))
    private fun book()=CommerceBook("Buyer",listOf(MarketListing("item","原交易商品","约定说明","交付内容","建材",10000,3,"Seller","1000101",setOf(DeliveryMethod.Pickup),"出生点",imageUri="file:///cover.png")),{cash},{delta,_,_->cash+=delta},time)
    private fun rejected(book:CommerceBook):String {val id=book.buyMarket("buy","item",1,DeliveryMethod.Pickup,"出生点")!!;book.ship(id,"Seller");time.hours(24);book.requestRefund(id,"Buyer","交付有误，请协商");book.resolveRefund(id,"Seller",false,"已经按照约定交付");return id}
    private fun submit(book:CommerceBook,id:String)=book.requestIntervention(id,"Buyer","case",form())
    @Test fun rejectedRefundOpensInterventionWithSnapshotAndIdempotency(){val b=book();val id=rejected(b);assertTrue(b.order(id)!!.canIntervene);assertFalse(b.requestIntervention(id,"Seller","case",form()));assertTrue(submit(b,id));assertTrue(submit(b,id));assertFalse(b.requestIntervention(id,"Buyer","another",form()));assertFalse(b.requestIntervention(id,"Buyer","case",form().copy(description=reason)));assertEquals("原交易商品",b.order(id)!!.intervention!!.snapshot.title);assertEquals(1,b.orders.size);assertEquals(90000L,cash)}
    @Test fun pendingCaseStopsClockAndBothPartiesActions(){val b=book();val id=rejected(b);submit(b,id);assertEquals(48*3600000L,b.order(id)!!.pausedMillis);time.hours(200);b.advanceTime();assertNull(b.order(id)!!.deadlineMillis);assertFalse(b.confirmReceipt(id,"Buyer"));assertFalse(b.requestRefund(id,"Buyer","再次申请"));assertFalse(b.previewDeadline(id,"Buyer"));assertFalse(b.resolveRefund(id,"Seller",true));assertEquals(10000L,b.heldTotal);assertTrue(b.sellerPayments.isEmpty())}
    @Test fun partialDecisionSplitsEscrowExactlyAndCannotRunTwice(){val b=book();val id=rejected(b);submit(b,id);assertTrue(b.simulatePlatformDecision(id,PlatformDecision.PartialRefund,3500,reason));assertEquals(93500L,cash);assertEquals(6500L,b.sellerPayments["Seller"]);assertEquals(0L,b.heldTotal);assertEquals(3500L,b.order(id)!!.intervention!!.refunded);assertFalse(b.simulatePlatformDecision(id,PlatformDecision.FullRefund,0,reason));time.hours(200);b.advanceTime();assertEquals(93500L,cash);assertEquals(6500L,b.sellerPayments["Seller"])}
    @Test fun invalidPartialAmountsAndReasonsLeaveEscrowUntouched(){val b=book();val id=rejected(b);submit(b,id);for(n in listOf(-1L,0,10000,10001,Long.MAX_VALUE))assertFalse(b.simulatePlatformDecision(id,PlatformDecision.PartialRefund,n,reason));assertFalse(b.simulatePlatformDecision(id,PlatformDecision.FullRefund,0,"太短"));assertEquals(90000L,cash);assertEquals(10000L,b.heldTotal)}
    @Test fun platformFullRefundDoesNotAssumeDeliveredItemsReturned(){val b=book();val id=rejected(b);submit(b,id);assertTrue(b.simulatePlatformDecision(id,PlatformDecision.FullRefund,0,reason));assertEquals(100000L,cash);assertEquals(2,b.listings.single().stock);assertEquals(RefundState.Approved,b.order(id)!!.refund);assertTrue(b.sellerPayments.isEmpty());assertEquals(0L,b.heldTotal)}
    @Test fun releasePaysAllEscrowOnce(){val b=book();val id=rejected(b);submit(b,id);assertTrue(b.simulatePlatformDecision(id,PlatformDecision.ReleaseToPayee,0,reason));assertEquals(10000L,b.sellerPayments["Seller"]);assertEquals(90000L,cash);assertFalse(b.confirmReceipt(id,"Buyer"))}
    @Test fun continueResumesOriginalRemainingTime(){val b=book();val id=rejected(b);submit(b,id);time.hours(100);assertTrue(b.simulatePlatformDecision(id,PlatformDecision.ContinueFulfillment,0,reason));assertEquals(time.millis()+48*3600000L,b.order(id)!!.deadlineMillis);time.hours(47);b.advanceTime();assertEquals(10000L,b.heldTotal);time.hours(1);b.advanceTime();assertEquals(10000L,b.sellerPayments["Seller"])}
    @Test fun alreadySettledCaseCannotRefundOrClawBack(){val b=book();val id=rejected(b);b.confirmReceipt(id,"Buyer");assertTrue(submit(b,id));assertFalse(b.order(id)!!.intervention!!.fundsHeldForReview);assertFalse(b.simulatePlatformDecision(id,PlatformDecision.FullRefund,0,reason));assertFalse(b.simulatePlatformDecision(id,PlatformDecision.ReleaseToPayee,0,reason));assertTrue(b.simulatePlatformDecision(id,PlatformDecision.ManualRecovery,0,reason));assertEquals(90000L,cash);assertEquals(10000L,b.sellerPayments["Seller"])}
    @Test fun restoredPendingCaseStaysFrozenAndResolvedCaseStaysFinal(){val b=book();val id=rejected(b);submit(b,id);val restored=book();restored.restore(b.listings.toList(),b.orders.toList(),b.notices.toList(),b.sellerPayments.toMap(),b.nextSequence);time.hours(200);restored.advanceTime();assertTrue(restored.order(id)!!.platformPending);assertEquals(10000L,restored.heldTotal);restored.simulatePlatformDecision(id,PlatformDecision.PartialRefund,4000,reason);val final=book();final.restore(restored.listings.toList(),restored.orders.toList(),restored.notices.toList(),restored.sellerPayments.toMap(),restored.nextSequence);assertFalse(final.simulatePlatformDecision(id,PlatformDecision.FullRefund,0,reason));final.advanceTime();assertEquals(94000L,cash);assertEquals(6000L,final.sellerPayments["Seller"])}
    @Test fun concurrentVerdictsOnlyExecuteOne(){val b=book();val id=rejected(b);submit(b,id);val start=CountDownLatch(1);val pool=Executors.newFixedThreadPool(2);try{val futures=listOf(PlatformDecision.FullRefund,PlatformDecision.ReleaseToPayee).map{d->pool.submit<Boolean>{start.await();b.simulatePlatformDecision(id,d,0,reason)}};start.countDown();assertEquals(1,futures.count{it.get(3,TimeUnit.SECONDS)});assertEquals(10000L,cash-90000+(b.sellerPayments["Seller"] ?: 0));assertEquals(0L,b.heldTotal)}finally{pool.shutdownNow()}}
    @Test fun formValidationChecksEvidenceDescriptionAndExactAmountBounds(){assertFalse(form().copy(description="短").valid(10000));assertFalse(form().copy(evidence=List(11){"file:///evidence$it"}).valid(10000));assertFalse(form().copy(wish=InterventionWish.PartialRefund,requestedRefund=10000).valid(10000));assertTrue(form().copy(wish=InterventionWish.PartialRefund,requestedRefund=1).valid(10000))}
    private fun commissions()=CommissionBook("Buyer",{cash},{delta,_,_->cash+=delta},time)
    private fun rejectedCommission(b:CommissionBook,complete:Boolean=false):String{val id=b.publish("pub",CommissionDraft("修建花园","按约定布置灯笼和花圃","出生点",10000,48,Urgency.Normal,"file:///cover.png"))!!;b.accept(id,"Worker");if(complete)b.complete(id,"Worker","按约定完成，请检查");time.hours(12);b.requestRefund(id,"Buyer","交付不符，请协商");b.resolveRefund(id,"Worker",false,"已按约定完成工作");return id}
    @Test fun activeCommissionFreezesAndCannotCompleteDuringReview(){val b=commissions();val id=rejectedCommission(b);assertTrue(b.requestIntervention(id,"Buyer","case",form()));assertFalse(b.complete(id,"Worker","仍提交完成"));time.hours(200);b.advanceTime();assertEquals(10000L,b.heldForUser);assertTrue(b.simulatePlatformDecision(id,PlatformDecision.NoAction,0,reason));assertEquals(time.millis()+36*3600000L,b.find(id)!!.deadlineMillis);assertTrue(b.complete(id,"Worker","按判决继续后完成"))}
    @Test fun completedCommissionPartialRefundHasNoLaterAutoSettlement(){val b=commissions();val id=rejectedCommission(b,true);assertTrue(b.requestIntervention(id,"Buyer","case",form()));assertFalse(b.confirm(id,"Buyer"));assertTrue(b.simulatePlatformDecision(id,PlatformDecision.PartialRefund,2500,reason));assertEquals(92500L,cash);assertEquals(7500L,b.payments["Worker"]);time.hours(300);b.advanceTime();assertFalse(b.simulatePlatformDecision(id,PlatformDecision.ReleaseToPayee,0,reason));assertEquals(7500L,b.payments["Worker"]);assertEquals(0L,b.heldForUser)}
    @Test fun restoredCommissionCaseRefundsOnce(){val b=commissions();val id=rejectedCommission(b,true);b.requestIntervention(id,"Buyer","case",form());val restored=commissions();restored.restore(b.entries.toList(),b.payments.toMap(),b.nextSequence);time.hours(300);restored.advanceTime();assertTrue(restored.find(id)!!.platformPending);assertTrue(restored.simulatePlatformDecision(id,PlatformDecision.FullRefund,0,reason));assertEquals(100000L,cash);assertEquals(CommissionStage.Cancelled,restored.find(id)!!.stage);assertFalse(restored.simulatePlatformDecision(id,PlatformDecision.FullRefund,0,reason));assertTrue(restored.payments.isEmpty())}
    @Test fun settledCommissionNeedsManualRecovery(){val b=commissions();val id=rejectedCommission(b,true);b.confirm(id,"Buyer");assertTrue(b.requestIntervention(id,"Buyer","case",form()));assertFalse(b.simulatePlatformDecision(id,PlatformDecision.FullRefund,0,reason));assertTrue(b.simulatePlatformDecision(id,PlatformDecision.ManualRecovery,0,reason));assertEquals(10000L,b.payments["Worker"]);assertEquals(90000L,cash)}
}
